name: Build & Test
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate workflows
        run: |-
          npm i
          npm run generate-workflows
          if [[ $(git diff --name-only .github/workflows/) ]]; then
                echo "Workflows are out of sync. Please regenerate them.";
                exit 1;
              fi
        shell: bash
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build for WASM
        run: cargo build --target wasm32-unknown-unknown --workspace
      - name: Run tests
        run: cargo test --workspace
